## Matrix computations in Numpy

In [1]:
import numpy as np

Basic matrix arithmetics like

    Matrix addition
    Matrix subtraction
    Matrix multiplication
    Scalar product
    Cross product
    and other operations on matrices



The arithemtic standard Operators

    +
    -
    *
    /
    **
    %

are applied on the elements, this means that the arrays have to have the same size. 

In [2]:
x = np.array([1,5,2])
y = np.array([7,4,1])

In [3]:
x + y

array([8, 9, 3])

In [4]:
x * y

array([ 7, 20,  2])

In [5]:
x - y

array([-6,  1,  1])

In [6]:
x / y

array([0.14285714, 1.25      , 2.        ])

In [7]:
x % y

array([1, 1, 0], dtype=int32)

In mathematics, the dot product is an algebraic operation that takes two coordinate vectors of equal size and returns a single number. The result is calculated by multiplying corresponding entries and adding up those products. The name "dot product" stems from the fact that the centered dot "·" is often used to designate this operation.

In [8]:
x = np.array([1,2,3])
y = np.array([-7,8,9])
dot = np.dot(x,y)
np.dot(x,y)

36

### Matrices

The matrix objects are a subclass of the numpy arrays (ndarray). The matrix objects inherit all the attributes and methods of ndarray. Another difference is that numpy matrices are strictly 2-dimensional, while numpy arrays can be of any dimension, i.e. they are $n$-dimensional.

The most important advantage of matrices is that they provide convenient notations for the matrix mulitplication. If $X$ and $Y$ are two Matrices than $X * Y$ defines the matrix multiplication. While on the other hand, if $X$ and $Y$ are ndarrays, $X * Y$ define an element by element multiplication. 

In [9]:
x = np.array( ((2,3), (3, 5)) )
y = np.array( ((1,2), (5, -1)) )

In [10]:
x * y

array([[ 2,  6],
       [15, -5]])

In [11]:
x = np.matrix( ((2,3), (3, 5)) )
y = np.matrix( ((1,2), (5, -1)) )

In [12]:
x * y

matrix([[17,  1],
        [28,  1]])

If we want to perform matrix multiplication with two numpy arrays (ndarray), we have to use the dot product:

In [13]:
x = np.array( ((2,3), (3, 5)) )
y = np.array( ((1,2), (5, -1)) )
np.dot(x,y)

array([[17,  1],
       [28,  1]])

Alternatively, we can cast them into matrix objects and use the "\*" operator: 

In [14]:
np.mat(x) * np.mat(y)

matrix([[17,  1],
        [28,  1]])

### Computing determinants and eigenvalues

In [15]:
H = np.matrix( ((3,-1,0), (-1,3,0), (0,0,5)) )
eigenvalues, eigenvectors = np.linalg.eig(H)

In [16]:
eigenvalues

array([4., 2., 5.])

In [17]:
determinant = np.linalg.det(H)

In [18]:
determinant

40.000000000000014